### PR TITLE
change the PingAsync logic

### PR DESCRIPTION
**Pull request by DHclly**
resolve if can't connect to clam av server ,
PingAsync will throw a  exception,it should be return false.

Signed-off-by: DHclly <335121817@qq.com>

### CODE REVIEW

**Comment by tekmaven** [comment]
Hello and thanks for the contribution, it's really appreciated!  There are many users of this package and I've done my best to avoid breaking changes to the existing API.  Users could depend on this to throw in some cases, so I think we should keep this method as-is and create a new method called `TryPingAsync`, which adds the try/catch logic.  Or you can just wrap your call to `PingAsync` in a try/catch.

**Comment by DHclly** [comment]
Thank you for your reply , I add the method `TryPingAsync` and add some tip at method `PingAsync`

**Comment by tekmaven** [comment]
Thanks @DHclly I will incorporate this into the next release shortly.

**Comment by douglasg14b** [comment]
@tekmaven When will this be merged? The exception throwing behavior of `TryAsync` is far from ideal and makes for very verbose and sometimes nested try/catch blocks

**Pull request merged**
