### PR TITLE
Add support for .NET Standard 2.0

### PR DESCRIPTION
**Pull request by ez5504**
I updated the project file to target .NET 4.5 and .NET Standard 2.0 and changed it to package as a single NuGet file. I had originally planned to target .NET Standard 1.3 to 1.6 and .NET 4.5 to 4.6 (as you will probably see), but it felt like too much since targeting just these 2 covers the majority.
Hopefully this helps more than just me!

### CODE REVIEW

**Comment by tekmaven** [comment]
Thanks so much for the PR!!  We need to get this building in AppVeyor before it can get accepted.  Could you take a look why it failed?

**Comment by tekmaven** [comment]
Thanks for checking into that.  It looks like they will have an image with 15.3 soon.  I will look out for that and test/release the package when they get that issue updated.

As far as the code changes, everything looks great.  I appreciate the help here.

**Comment by ez5504** [comment]
The image has been released to AppVeyor. I played around with it and I was finally able to get the project to build after tweaking the build script and doing some setup first in AppVeyor. 

Let me know if you need any help getting it to build.

**Comment by tekmaven** [comment]
I'm testing locally and reviewing the source code changes.  Why did you put the usings inside of the namespace?  Personal preference? Is there something in .NET Standard that makes that preferable?

**Comment by ez5504** [comment]
Primarily personal preference. It's something I'm used to doing, so I did it out of habit. I don't believe there's anything in .NET Standard that makes it better or worse.

**Comment by tekmaven** [comment]
Thanks!  I've added a .NET Core 2.0 console test app, changed the test apps to use `async Main()`, updated the readme, and merged your changes in.

New package is released and show should up on nuget.org shortly!

**Pull request closed without merging**
