### PR TITLE
Added async api methods

### PR DESCRIPTION
**Pull request by garethbudden**
Hope this will be of some use...
I've updated the project to use .net 4.5 but if need be I can downgrade it again to .net 4.0. 
As you can see at present I've just added another set of Async methods so as not to break backwards comparability - or would you rather release an async only version of the API and call it a nuget v2?

### CODE REVIEW

**Comment by garethbudden** [comment]
Hi - any feedback on this?

**Comment by tekmaven** [comment]
Hey!  Thanks for the PR!  Aync/await is awesome and it's great that the client can be made fully async.  After giving it some thought, I think we should go with the async only version and rev the major version number.

**Comment by garethbudden** [comment]
@tekmaven I've removed those sync API's as requested so we're all async'd up!

**Comment by tekmaven** [comment]
Thanks!  I have merged your changes and released nuget package 3.0!

**Pull request closed without merging**
